version: "3.8"

services:
  model:
    build: ./model
    ports:
      - "5000:5000"
    networks:
      - app_network

  frontend:
    build: ./
    ports:
      - "80:80"
    depends_on:
      - model
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
